### ISSUE TITLE
API update: Report versioning

### ISSUE THREAD

**Issue by zedtux** [iscreen/apple_reporter#5]
Here is an extract of the email sent from Apple to their customers:

> Report versioning.
>
> You can now specify which version of a report to download.
> Specify version 1_1 in your Reporter command to download the new version of Apple Music Summary Streams, Apple Music Detail Streams, and Apple Music Content reports.
> 
> Detailed information about these updates are available in Resources and Help.
>
> Review the changes and complete any necessary system updates before January 17, 2018.
> After this date, you must specify a version number to download reports using Reporter.

So it looks like this gem should be updated in order to include the API version now.

**Comment by iscreen** [comment]
Hi @zedtux ,
Thank you for the information, but I do not see any update about version parameter in [official document](https://help.apple.com/itc/appsreporterguide).

**Comment by zedtux** [comment]
@iscreen have a look to http://help.apple.com/itc/contentreporterguide/en.lproj/static.html#apd337746680, the versioning is well described.

Also since this month, my import is failing with the error code 213 from the Apple API ... I don't know if there is link to their new version ... but I don't know yet how to figure out it.

**Comment by iscreen** [comment]
@zedtux actually you can assign version when you construct object
```
reporter = AppleReporter::Finance.new(
  user_id: 'your user id', 
  access_token: 'your access token'
  version: '1_0'
)
```
however I had saw the default version value is different with document, I will change it.

**Comment by zedtux** [comment]
Okay, cool.

**Comment by zedtux** [comment]
@iscreen I'm facing the issue that all the reports I'm trying to downloads are failing with the error 213 (There were no sales for the date specified) since this month.

I'm requesting the report for period 2 and year 2018 (based on the Apple fiscal calendar, it should be fine).

Are experiencing any similar issues?

**edit:** I tried to set the version as you documented but it's still not working :(

**Comment by zedtux** [comment]
Sorry @iscreen but could you please have a look at my comment?

**Comment by iscreen** [comment]
@zedtux I don't know why you want to fetch the future report, but it's work for me.
however if you can put on your code snippet maybe I can help to find out the problem.

**Comment by zedtux** [comment]
Oh, looking again to [the Apple Fiscal Calendar](https://i.stack.imgur.com/oHQYI.jpg), I realised that the year has to be incremented at period 5 ...

Okay, thank you @iscreen, I will update my code accordingly.
