### ISSUE TITLE
problem to receive the data of apple_reporter

### ISSUE THREAD

**Issue by arabakevin** [iscreen/apple_reporter#8]
Hi all,
I use apple_reporter since several months.
Since the begin of 2018 i don't receive anything file. 
I have verified the version and the date of apples fiscal
I use this command to  02/2018
'''
report = reporter.get_report(
  vendor_number: 'your vender id',
  region_code: 'US',
  report_type: 'Financial',
  fiscal_year: '2019',
  fiscal_period: '04'
)
'''
And i use too
 '''
reporter = AppleReporter::Finance.new(
  user_id: 'your user id', 
  access_token: 'your access token'
  version: '1_1'
)
'''
Thanks for your help.

**Comment by arabakevin** [comment]
please you can see my previous comment please.
Thanks a lot

**Comment by iscreen** [comment]
@arabakevin 
Why you want to fetch fiscal_year from 2019?

**Comment by arabakevin** [comment]
Thanks.
But if we see the apple's calendar the number of the year is the current year + 1.
Perhaps, I can be wrong but if we can upload the information of February 2018 I must indicate 04 for the month and 2019 for the year no ?

**Comment by iscreen** [comment]
I'm not sure, but when I fetch 2019, I got error, because my fiscal year not include 2019,   
however you can check you fiscal year in [itc](https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/jumpTo?page=fiscalcalendar) 
```
{"Error"=>{"Code"=>"213", "Message"=>"There were no sales for the date specified."}} 
```

**Comment by arabakevin** [comment]
ok. And to have the period February 2018 you have use the parameters 04 for the month and 2018 for the month is it right ??
Thanks yet.

**Comment by iscreen** [comment]
@arabakevin 
Yes, According to [fiscal Year 2018 Accounting Calendar](https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/jumpTo?page=fiscalcalendar), Now (2018/02/26) is Q2 and period is 4.
